# Generated by Django 2.2.7 on 2019-12-25 17:42

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
