# Generated by Django 2.2.7 on 2019-12-26 19:06

import django.core.validators
from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20191225_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='batch_year',
            field=models.IntegerField(default=user_auth.models.current_year, validators=[django.core.validators.MinValueValidator(1900), user_auth.models.max_value_current_year], verbose_name='year'),
        ),
    ]
