# Generated by Django 2.2.7 on 2019-12-26 19:23

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20191226_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('BT', 'B.Tech'), ('MT', 'M.Tech'), ('S', 'Staff'), ('AL', 'Alumni'), ('O', 'Others')], default='Others', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('GEN', 'General'), ('CSE', 'Computer Science And Engineering'), ('Arch', 'Architecture'), ('ECE', 'Electronics and Communication Engineering'), ('PE', 'Production Engineering'), ('CHE', 'Chemical Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MEC', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='batch_year',
            field=models.IntegerField(default=user_auth.models.current_year, help_text='Pass out year', verbose_name='Batch Year'),
        ),
    ]
