# Generated by Django 2.2.7 on 2019-12-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20191226_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('BT', 'B.Tech'), ('MT', 'M.Tech'), ('S', 'Staff'), ('AL', 'Alumni'), ('O', 'Others')], default='Others', help_text='Ongoing', max_length=100),
        ),
    ]
