# Generated by Django 2.2.7 on 2019-12-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20191226_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('BT', 'B.Tech'), ('MT', 'M.Tech'), ('S', 'Staff'), ('AL', 'Alumni'), ('O', 'Others')], default='O', help_text='Ongoing', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('GEN', 'General'), ('CSE', 'Computer Science And Engineering'), ('Arch', 'Architecture'), ('ECE', 'Electronics and Communication Engineering'), ('PE', 'Production Engineering'), ('CHE', 'Chemical Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MEC', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], default='GEN', max_length=100),
        ),
    ]
