# Generated by Django 2.2.7 on 2019-12-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_profile_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_addr',
            field=models.BooleanField(default=False),
        ),
    ]
