# Generated by Django 2.2.7 on 2019-12-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_profile_hide_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hide_addr',
            field=models.BooleanField(default=False, help_text='Hides Address and phone number'),
        ),
    ]
