# Generated by Django 2.2.7 on 2019-12-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
