# Generated by Django 2.2.7 on 2019-12-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_posts_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image1',
            field=models.ImageField(default='default.png', upload_to='projects'),
        ),
        migrations.AddField(
            model_name='posts',
            name='image2',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='posts',
            name='image3',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
