# Generated by Django 2.2.7 on 2019-12-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20191223_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
