# Generated by Django 2.2.7 on 2019-12-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20191224_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='subtitle',
            field=models.CharField(default='Fantastic Project', max_length=500),
        ),
    ]
