# Generated by Django 2.2.7 on 2019-12-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20191225_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='documents',
            field=models.FileField(blank=True, upload_to='project_doc'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image1',
            field=models.ImageField(default='default.png', upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image2',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image3',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
